### ISSUE TITLE
Upgrading OAuth2

### ISSUE THREAD

**Issue by reggi** [notmaintained/shopify_api#10]
In you example that includes "If your migrating from legacy auth", are you suggesting not to run through the database, rather just convert it every time to a new code?

I need to implement OAuth2 from https://github.com/sandeepshetty/shopify.php and it seems like a pain. I'm using codeigniter, and I haven't coded anything in php in around a year.

Any advice? I'd love if I could just drop the new library in, but I'm guessing sadly that's not the case.

**Comment by reggi** [comment]
Help me Obi Wan Kinobi, you're my only hope. Anything on this matter? I'm about to pull two apps from the app store.

**Comment by sandeepshetty** [comment]
:) I'll be on this tonight (my time). Have to migrate my app as well.

**Comment by sandeepshetty** [comment]
@reggi I've committed a [quick hack](https://github.com/sandeepshetty/shopify.php/commit/9a5eef6712008312196baad376dc80e26a8d0e0f) to shopify.php for you, to keep your existing legacy apps running. It does not support new OAuth based installs but just by replacing your existing shopify.php with the latest one and switching the app to use OAuth in the Shopify app panel will keep it running.
