### ISSUE TITLE
Example use

### ISSUE THREAD

**Issue by bluetidepro** [notmaintained/shopify_api#3]
Would it be possible to add a folder to the repo that has an example app using this client? I would really appreciate seeing a proper setup using this client class! Thanks! :)

**Comment by shaangola** [comment]
Please provide example app using this api so that we can also make good use of it...would be very helpful..

**Comment by sandeepshetty** [comment]
[Latest version](https://github.com/phpish/shopify) has an [example app](https://github.com/phpish/shopify-skeleton).
