### ISSUE TITLE
Using shopify_api PHP library with Symfony2

### ISSUE THREAD

**Issue by zstiggz** [notmaintained/shopify_api#4]
Hey Sandeep,

I just wanted to let you know that the following line (line 2 of client.php) throws a 500 internal server error with the Symfony2 framework

```
require 'vendor/autoload.php';
```

Removing this line fixes the problem, since Symfony2 uses composer by default and has its own unique method of generating autoload.php.

**Comment by wesray** [comment]
Same with most frameworks - Removing it in Laravel 4 also fixes it.

**Comment by sandeepshetty** [comment]
This looks likes it's the same as #1. I'll push a fix in a bit after some testing.

**Comment by fform** [comment]
Just came across this for FuelPHP.

Why would you require the composer autoloader from inside your library?

Considering this is the linked library from Shopify's docs, would you mind removing that line and pushing a new version?

**Comment by wesray** [comment]
@fform just fork it and remove the line and add it to composer for now.  It's been like this forever.  Or put in a PR
