### ISSUE TITLE
Problem with raising exceptions

### ISSUE THREAD

**Issue by tomkerswill** [notmaintained/shopify_api#5]
I'm using your Shopify_API code to work with Shopify, and have gone through the steps in readme. I am having a problem with the example code, though. 

I am using the latest code from Github (https://github.com/sandeepshetty/shopify_api) installed using composer.

Here is the error:

Fatal error: Class 'sandeepshetty\shopify_api\ApiException' not found in /srv/www/cassavarepublic_paga/releases/20130614105446/vendor/sandeepshetty/shopify_api/client.php on line 76

I'm wondering if this is a bug, and whether the ApiException needs to be defined somewhere?

Thanks so much in advance,

Tom

**Comment by sandeepshetty** [comment]
This does look like a bug that #6 should fix. I'll merge this in a bit after some testing.

**Comment by tomkerswill** [comment]
Just to confirm I did a manual merge of #6 on my fork and everything has been working really well.

**Comment by sandeepshetty** [comment]
This issue and more fixed in the [latest version](https://github.com/phpish/shopify)
