### ISSUE TITLE
Cannot pull this with Composer

### ISSUE THREAD

**Issue by Cleanse** [notmaintained/shopify_api#7]
I am getting the following error:

Failed to clone https://github.com/sandeepshetty/wcurl.git, git was not found, check that it is installed and in your PATH env.

**Comment by sheetalp** [comment]
I am having the same issue on a windows machine, were you able to resolve it?

**Comment by keithmancuso** [comment]
yea not sure why the code isnt just in the repo?  why have a public repo with just a composer file in it?

**Comment by sandeepshetty** [comment]
Adding "minimum-stability": "dev" in the root package should solve this. There are others ways to do this as well till I start tagging releases. See: https://igor.io/2013/02/07/composer-stability-flags.html
