### ISSUE TITLE
Invalid exception

### ISSUE THREAD

**Issue by joshribakoff** [notmaintained/shopify_api#9]
Pass a bad access token and you have an error on line 74:
ApiException

If I grep the code, I find the definition of that class nowhere in sight.

**Comment by joshribakoff** [comment]
You also throw WcurlException, which isn't imported into the namespace, so that produces an error as well instead of throwing the exception as intended

**Comment by geoffnin** [comment]
I also have encountered this, Changing ApiException to Exception on line 76 of client.php makes it behave

**Comment by sandeepshetty** [comment]
This issue and more fixed in the [latest version](https://github.com/phpish/shopify)
